
name: Hecho por edilberto

on:
  push:
    branches: [ "main" ]

jobs:
  uthh:  
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v5 
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run build

        
